### PR TITLE
Dev designs - partial

### PR DESCRIPTION
**Pull request by Rajandeep98**
- Added Card for landing page buttons
- Added Footer Links 'release notes and hours of availability'
- responsive per design instructions

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-164-ih04tovw.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-164-ih04tovw.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-164-ih04tovw.web.app

**Review by pwei1018 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-164-ih04tovw.web.app

**Pull request closed without merging**
