### PR TITLE
Content Updates 

### PR DESCRIPTION
**Pull request by Rajandeep98**
Content Updates

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-163-phfrf07s.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-163-phfrf07s.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-163-phfrf07s.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-163-phfrf07s.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-163-phfrf07s.web.app

**Review by bolyachevets — APPROVED** [review]

**Review by thorwolpert — COMMENTED** [review]
I think this can be closed, and just add the products to the ignore list

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-163-phfrf07s.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-163-phfrf07s.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-163-phfrf07s.web.app

**Pull request merged**
