### PR TITLE
Header devsite

### PR DESCRIPTION
**Pull request by Rajandeep98**
Header Design Updates
https://github.com/bcgov/entity/issues/24325

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-166-0gn6bhn2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-166-0gn6bhn2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-166-0gn6bhn2.web.app

**Review by pwei1018 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-166-euj414i5.web.app

**Review by sameer0422 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-166-euj414i5.web.app

**Pull request merged**
