### PR TITLE
Breadcrumb devsite

### PR DESCRIPTION
**Pull request by Rajandeep98**
- Add breadcrumb component 
   (ref. code: nuxt/layers/core/app/components/Connect )

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-167-liaofvqk.web.app

**Review by pwei1018 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-167-1rexgsiy.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-167-1rexgsiy.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-167-1rexgsiy.web.app

**Review by sameer0422 — APPROVED** [review]

**Pull request merged**
