### PR TITLE
documents page design updates

### PR DESCRIPTION
**Pull request by Rajandeep98**
- updated designs for side navigation menu and docs page
- removed contents page navigation

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-173-b3rpfk63.web.app

**Review by sameer0422 — APPROVED** [review]
Looks good

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-173-b3rpfk63.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://developer-connect-dev--pr-173-b3rpfk63.web.app

**Pull request merged**
